import { OfficerContact } from '../types';

export const SEED_OFFICER_CONTACTS: OfficerContact[] = [
  {
    id: 'officer_nat_agritex',
    name: 'AGRITEX National Advisory Desk',
    role: 'mudhumeni',
    roleTitle: 'Department of Agricultural Technical & Extension Services',
    phone: '+263242706081',
    whatsapp: '+263772100200',
    email: 'agritex@moa.gov.zw',
    province: 'Harare',
    district: 'Harare Central',
    wardOrArea: 'Ngungunyana Building, 1 Borrowdale Road',
    address: 'Ministry of Lands, Agriculture, Fisheries, Water & Rural Development',
    specialization: 'National crop calendars, Pfumvudza/Intwasa distribution, fall armyworm alerts',
    isCustom: false,
    notes: 'Official government extension hotline for all provinces.',
    createdAt: 1700000000000,
  },
  {
    id: 'officer_nat_dvs',
    name: 'Department of Veterinary Services (DVS) HQ',
    role: 'vet_officer',
    roleTitle: 'Chief Veterinary Officer & Disease Control',
    phone: '+263242791255',
    whatsapp: '+263773400500',
    email: 'vetcontrol@dvs.gov.zw',
    province: 'Harare',
    district: 'Harare Central',
    wardOrArea: '18 Borrowdale Rd, Agricultural Research Complex',
    address: 'DVS Emergency Epizootic Surveillance',
    specialization: 'Anthrax, Theileriosis (January Disease), Foot & Mouth, Rabies movement permits',
    isCustom: false,
    notes: 'National emergency notification line for livestock disease outbreaks and quarantine enforcement.',
    createdAt: 1700000000001,
  },
  {
    id: 'officer_masheast_marondera',
    name: 'Marondera District AGRITEX Office',
    role: 'agronomist',
    roleTitle: 'District Agricultural Extension Officer (DAEO)',
    phone: '+2637922245',
    whatsapp: '+263774889911',
    province: 'Mashonaland East',
    district: 'Marondera',
    wardOrArea: 'Marondera Government Complex, Ward 4',
    address: 'Stand 14, 4th Street, Marondera',
    specialization: 'Maize, Soybeans, Seed potato certification, Soil testing',
    isCustom: false,
    notes: 'Provides ward extension officers (Madhumeni) for Dombotombo, Wenimbi, and surrounding farming areas.',
    createdAt: 1700000000002,
  },
  {
    id: 'officer_masheast_vet',
    name: 'Marondera Veterinary Diptank Station',
    role: 'vet_officer',
    roleTitle: 'Livestock Development Specialist & Vet Officer',
    phone: '+2637924401',
    whatsapp: '+263712334455',
    province: 'Mashonaland East',
    district: 'Marondera',
    wardOrArea: 'Marondera Rural Diptank Cluster',
    address: 'Old Mutare Road Veterinary Center',
    specialization: 'Tick-borne disease dipping, cattle brands, Brucellosis testing, Newcastle poultry vaccines',
    isCustom: false,
    notes: 'Handles 5-5-4 dipping schedules and issuing movement permits to abattoirs.',
    createdAt: 1700000000003,
  },
  {
    id: 'officer_mashwest_chinhoyi',
    name: 'Chinhoyi AGRITEX & Grain Advisory',
    role: 'agronomist',
    roleTitle: 'Senior Agronomist (Mudhumeni Mukuru)',
    phone: '+263672124500',
    whatsapp: '+263775112233',
    province: 'Mashonaland West',
    district: 'Chinhoyi / Makonde',
    wardOrArea: 'Makonde Ward 8, Magamba Way',
    address: 'Provincial Agricultural Offices, Chinhoyi',
    specialization: 'Commercial maize, Wheat winter irrigation, Cotton, Fall Armyworm spraying',
    isCustom: false,
    notes: 'Field visits and pest diagnosis support for Makonde, Banket, and Mhangura farmers.',
    createdAt: 1700000000004,
  },
  {
    id: 'officer_mashwest_vet',
    name: 'Makonde District Veterinary Officer',
    role: 'vet_officer',
    roleTitle: 'Chiremba weMhuka / Veterinary Surgeon',
    phone: '+263672122110',
    whatsapp: '+263776223344',
    province: 'Mashonaland West',
    district: 'Chinhoyi',
    wardOrArea: 'Chinhoyi Rural / Alaska Area',
    address: 'DVS Clinic, Chinhoyi Industrial Site',
    specialization: 'Beef cattle health, Artificial Insemination (AI), Lumpy Skin treatment, Pig health',
    isCustom: false,
    notes: 'On-call for difficult calving, post-mortem livestock inspections, and antibiotic prescriptions.',
    createdAt: 1700000000005,
  },
  {
    id: 'officer_manicaland_mutare',
    name: 'Manicaland AGRITEX & Horticulture Desk',
    role: 'agronomist',
    roleTitle: 'Horticulture & Crops Extension Officer',
    phone: '+263202061200',
    whatsapp: '+263777334455',
    province: 'Manicaland',
    district: 'Mutare / Mutasa',
    wardOrArea: 'Mutare City / Mutasa Ward 2',
    address: '2nd Floor, Government Building, Robert Mugabe Way, Mutare',
    specialization: 'Tomatoes, Cabbage, Macadamia, Banana, Irrigation systems, Soil PH testing',
    isCustom: false,
    notes: 'Supports Honde Valley, Odzi, and Mutare peri-urban growers.',
    createdAt: 1700000000006,
  },
  {
    id: 'officer_manicaland_vet',
    name: 'Chipinge & Mutare Livestock Veterinary Desk',
    role: 'vet_officer',
    roleTitle: 'Veterinary Livestock Officer',
    phone: '+263272042100',
    whatsapp: '+263778445566',
    province: 'Manicaland',
    district: 'Chipinge',
    wardOrArea: 'Middle Sabi & Chipinge Town',
    address: 'Veterinary Services Complex, Chipinge',
    specialization: 'Dairy cow health, mastitis management, goat deworming, poultry disease vaccination',
    isCustom: false,
    notes: 'Handles high-rainfall dairy management and intensive small ruminants.',
    createdAt: 1700000000007,
  },
  {
    id: 'officer_midlands_gweru',
    name: 'Midlands Provincial AGRITEX Center',
    role: 'mudhumeni',
    roleTitle: 'Mudhumeni weDunhu / Provincial Extension Officer',
    phone: '+263542223400',
    whatsapp: '+263779556677',
    province: 'Midlands',
    district: 'Gweru',
    wardOrArea: 'Gweru Central & Lower Gweru',
    address: 'Government Complex, 7th Street, Gweru',
    specialization: 'Drought-tolerant grains (Sorghum, Pearl Millet), Maize, Groundnuts, Fodder crops',
    isCustom: false,
    notes: 'Guidance on dry-region farming and conservation agriculture (Pfumvudza).',
    createdAt: 1700000000008,
  },
  {
    id: 'officer_midlands_vet',
    name: 'Gweru Veterinary & Cattle Dipping Office',
    role: 'vet_officer',
    roleTitle: 'District Veterinary Officer (Chiremba weMhuka)',
    phone: '+263542221800',
    whatsapp: '+263771667788',
    province: 'Midlands',
    district: 'Gweru / Somabhula',
    wardOrArea: 'Somabhula & Vungu Ward 11',
    address: 'Lincoln Road Veterinary Depot, Gweru',
    specialization: 'January disease dipping, Quarter evil (Blackleg), Anthrax booster vaccinations',
    isCustom: false,
    notes: 'Provides emergency vaccine supply and diptank acariciding testing.',
    createdAt: 1700000000009,
  },
  {
    id: 'officer_masvingo_agritex',
    name: 'Masvingo District AGRITEX Office',
    role: 'agronomist',
    roleTitle: 'Agricultural Extension Supervisor',
    phone: '+263392262500',
    whatsapp: '+263772778899',
    province: 'Masvingo',
    district: 'Masvingo / Gutu',
    wardOrArea: 'Gutu Ward 15 / Masvingo Rural',
    address: 'Old Post Office Building, Masvingo',
    specialization: 'Small grains, Cowpeas, Sweet potato vines, Drip irrigation vegetable farming',
    isCustom: false,
    notes: 'Supports smallholder communal and A1/A2 farmers throughout Masvingo province.',
    createdAt: 1700000000010,
  },
  {
    id: 'officer_matnorth_lupane',
    name: 'Lupane / Matabeleland North Vet & Extension',
    role: 'livestock_specialist',
    roleTitle: 'Livestock Production & Extension Specialist',
    phone: '+2633892300',
    whatsapp: '+263773889900',
    province: 'Matabeleland North',
    district: 'Lupane',
    wardOrArea: 'Lupane Center / Ward 6',
    address: 'Provincial Government Complex, Lupane',
    specialization: 'Brahman and Indigenous Matabele cattle breeding, drought supplementary feeding, Bush clearance',
    isCustom: false,
    notes: 'Assists with livestock feeds, borehole water troughs, and pasture rotation.',
    createdAt: 1700000000011,
  },
];
